name: Build & Test #Name of the workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/included:8.0.0
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        uses: cypress-io/github-action@v2
        run: cd ./frontend
        with:
          start: cd .. && docker compose up -d --build
          wait-on: "http://localhost:3001"
          wait-on-timeout: 5000
          browser: chrome
          headless: true

        env:
          CI: true
