name: Build & Test #Name of the workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # - name: Install Node JS ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Build Docker stack
        run: docker compose up -d --build

      - name: Run Cypress tests
        run: cd ./frontend && ././node_modules/.bin/cypress

      - name: Run Postman tests
        run: newman run ONI.postman_collection.json
